---
title: "CL_Access_To_Healthcare_01"
author: "Group K"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,   results = "hide",  message = FALSE,   # hide package messages
  warning = FALSE)
```
#Loading Libraries
```{r}
library(dplyr)
library(tidyr)
library(stringr)
library(readr)
library(here)
library(ggplot2)

getwd()
list.files("data/raw_data")
```

```{r}
acc_df <- read_csv(here("raw_data", "access-to-health-care_national_zaf.csv"))
```

## Display Dataset content
```{r, results='hold'}
head(acc_df, 5)
```

## Remove the first row(meta data)
```{r, echo=TRUE}
acc_df <- acc_df[-1, ]
```
 
```{r}
dim(acc_df)
```

```{r}
dup_check <- acc_df %>%
  group_by(Indicator, SurveyYear, CharacteristicId, Value) %>%
  filter(n() > 1)

dup_check

```

```{r}
acc_df <- acc_df %>%
  distinct(Indicator, SurveyYear, CharacteristicId, Value, .keep_all = TRUE)

```

```{r}

data.frame(
  Column = names(acc_df),
  Missing_Percentage = paste0(round(colMeans(is.na(acc_df)) * 100, 2), "%")
  )

```

```{r}
data.frame(
  Column = names(acc_df),
  Missing_Data = paste0(colSums(is.na(acc_df)))
  )
```

## Check data types
```{r, results='hold'}
data.frame(
  Column = names(acc_df),
  paste0(sapply(acc_df, typeof))
)

```

```{r}
str(acc_df)

```
## Convert Data Types
```{r, echo=TRUE}
acc_df <- acc_df %>%
  mutate(
        Value = as.numeric(Value),
    Precision = as.numeric(Precision),
    SurveyYear = as.integer(SurveyYear),
    IndicatorOrder = as.integer(IndicatorOrder),
    CharacteristicId = as.integer(CharacteristicId),
    CharacteristicOrder = as.integer(CharacteristicOrder),
    IsTotal = as.logical(as.integer(IsTotal)),
    IsPreferred = as.logical(as.integer(IsPreferred)),
    SurveyYearLabel = as.integer(SurveyYearLabel),
    DenominatorWeighted = as.numeric(DenominatorWeighted),
    DenominatorUnweighted = as.numeric(DenominatorUnweighted),
  )
```
## Check for unique values
```{r, results='hold'}
library(dplyr)
library(purrr)

# Summary table: column name, number of unique values, sample of unique values
n_sample <- 3

summary_tbl <- acc_df %>%
  map_df(~ tibble(
    n_unique = n_distinct(.),
    sample_values = paste(head(unique(.), n_sample), collapse = ", ")
  ), .id = "column")


summary_tbl


```

#Drop the countries only one unqiue value: reason, there is no useful information - county is also always za
```{r}
acc_df <- acc_df %>%
 select(
     -ISO3, 
    -DHS_CountryCode, 
    -CountryName, 
    -SurveyId,
    -ByVariableId, 
    -ByVariableLabel, 
    -IsTotal,
    -RegionId, 
    -SurveyYearLabel, 
    -SurveyType,
    -CharacteristicOrder
  )
```

#Assumed pattern, the missing values can be filled with the previous non missing value in the opposite attribute
```{r}


library(dplyr)
library(tidyr)

acc_df <- acc_df %>%
  fill(DenominatorWeighted, DenominatorUnweighted, .direction = "down")

acc_df[
       c("DenominatorWeighted", "DenominatorUnweighted")]

```

```{r}
ggplot(acc_df, aes(x = DenominatorWeighted, y = DenominatorUnweighted)) +
  geom_point(alpha = 0.6, color = "steelblue") +
  labs(title = "Scatterplot for Outlier Detection",
       x = "Denominator Weighted",
       y = "Denominator Unweighted") +
  theme_minimal()


ggplot(acc_df, aes(y = DenominatorWeighted)) +
  geom_boxplot(fill = "lightblue", outlier.color = "red", outlier.shape = 16) +
  labs(title = "Boxplot of Denominator Weighted",
       y = "Denominator Weighted") +
  theme_minimal()




```


```{r}
dim(acc_df)
```
```{r}
write_csv(acc_df, here("cleaned_data", "access-to-healthcare_cleaned.csv"))
```