---
title: "EDA_Child_Mortality_Rates_National_03"
author: "Group K"
date: "`r Sys.Date()`"
output: pdf_document
---
```{r setup, echo=TRUE, warning=FALSE, message=FALSE}
library(readr)
library(ggplot2)
library(dplyr)
library(here)

getwd()
list.files("data/raw_data")
```

# Load data and show the structure 
```{r}
cmr_df <- read_csv(here("raw_data", "child-mortality-rates_national_zaf.csv"))
```
#Dislay the first and last 10 rows
```{r}
head(cmr_df, 50)

#tail(cmr_df, 10)
```

#Dimenison of the data
```{r}
dim(cmr_df)
```
#Provide a summary of the datset
```{r}
summary(cmr_df)
```
#Convert Value to a numeric
```{r}
cmr_df$Value <- as.numeric(cmr_df$Value)
```
#Find duplicated values 
```{r}
sum(duplicated(cmr_df))
```
#Inspect columns for missing/empty data as values and pecentages respectively
```{r}
colSums(is.na(cmr_df))
round(colMeans(is.na(cmr_df)) * 100, 2)
```

# Check for unique values
```{r}
sapply(cmr_df, function(x) length(unique(x)))

```
#Plots
```{r}

cmr_df$Value <- as.numeric(cmr_df$Value)
cmr_df$SurveyYear <- as.numeric(cmr_df$SurveyYear)

# Example: Bar plot of mortality indicators for a specific year
ggplot(cmr_df[cmr_df$SurveyYear == 1998, ], aes(x = Indicator, y = Value, fill = Indicator)) +
  geom_bar(stat = "identity") +
  theme_minimal() +
  labs(title = "Child Mortality Indicators(1998)",
       x = "Indicator",
       y = "Rate per 1000 births") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
ggsave("../outputs/visuals/cmr_bargraph.png", width = 6, height = 4)

#Outliers
boxplot(cmr_df$Value, main = "Outlier check for Values")

```

```{r}

cmr_df$Value <- as.numeric(cmr_df$Value)
cmr_df$SurveyYear <- as.numeric(cmr_df$SurveyYear)

ggplot(cmr_df, aes(x = factor(SurveyYear), y = Value, fill = Indicator)) +
  geom_bar(stat = "identity", position = "dodge") +
  theme_minimal() +
  labs(title = "Child Mortality Indicators (TS)",
       x = "Survey Year",
       y = "Rate per 1000 births",
       fill = "Indicator") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

ggsave("../outputs/visuals/cmr_timeseriesplot.png", width = 6, height = 4)

```

