---
title: "EDA_Symptoms_Of_Acute_Respiratory_Infection_11"
author: "Group K"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, echo=TRUE, warning=FALSE, message=FALSE}
library(readr)
library(ggplot2)
library(dplyr)
library(here)
library(tidyr)
library(knitr)
library(skimr)
library(tidyverse)
library(summarytools)

getwd()
list.files("data/raw_data")
```

# Load data and show the structure 
```{r}
ari_df <- read_csv(here("raw_data", "symptoms-of-acute-respiratory-infection-ari_national_zaf.csv"))
```
#Dislay the first and last 10 rows
```{r}
head(ari_df, 50)

#tail(ari_df, 10)
```
#remove first row
```{r}
ari_df[-1,]
```

#Dimenison of the data
```{r}
dim(ari_df)
```
#Provide a summary of the datset
```{r}
summary(ari_df)
```
#Find duplicated values 
```{r}
sum(duplicated(ari_df))
```
#Inspect columns for missing/empty data as values and pecentages respectively
```{r}
colSums(is.na(ari_df))
round(colMeans(is.na(ari_df)) * 100, 2)
```

# Check for unique values
```{r}
sapply(ari_df, function(x) length(unique(x)))

```


#Plots
```{r}
#incomplete



```
#Summary Table
```{r}

```

