---
title: "EDA_Access_To_Healthcare_National_01"
author: "Group K"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, echo=TRUE, warning=FALSE, message=FALSE}
library(readr)
library(ggplot2)
library(dplyr)
library(here)

getwd()
list.files("data/raw_data")
```

# Load data and show the structure 
```{r}
acc_df <- read_csv(here("raw_data", "anthropometry_national_zaf.csv"))
str(acc_df)
```
#Dislay the first and last 10 rows
```{r}
head(acc_df, 10)

tail(acc_df, 10)
```

#Dimenison of the data
```{r}
dim(acc_df)
```
#Provide a summary of the datset
```{r}
summary(acc_df)
```
#Convert Value to a numeric
```{r}
acc_df$Value <- as.numeric(acc_df$Value)
```
#Find duplicated values 
```{r}
sum(duplicated(acc_df))
```
#Inspect columns for missing/empty data as values and pecentages respectively
```{r}
colSums(is.na(acc_df))
round(colMeans(is.na(acc_df)) * 100, 2)
```

# Check for unique values
```{r}
sapply(acc_df, function(x) length(unique(x)))

```
#Plots
```{r}
#Histogram of Values

ggplot(acc_df, aes(x = Value)) +
geom_histogram(bins = 30, fill = "skyblue", color = "black") +
  labs(title = "Distribution of Indicator Values")


# Line graph by SurveyYear
ggplot(acc_df, aes(x = SurveyYear, y = Value, color = Indicator)) +
  geom_line(aes(group = Indicator)) +
  geom_point() +
  labs(title = "Indicator Trends Over Survey Years")

#Line plot for Values
ggplot(acc_df, aes(x = SurveyYear, y = Value)) +
  geom_line(color = "steelblue", linewidth = 1) +
  geom_point(color = "darkred", size = 2) +
  labs(title = "Trend of Values over Survey Years",
       x = "Survey Year",
       y = "Value") +
  theme_minimal()


#Outliers
boxplot(acc_df$Value, main = "Outlier check for Values")

range(acc_df$Value, na.rm = TRUE)
```

```{r}
acc_df[acc_df$Value < 0 | acc_df$Value > 100, c("Indicator", "Value")]

percent_df <- subset(acc_df, Value >= 0 & Value <= 100)

ggplot(percent_df, aes(x = Indicator, y = Value)) +
  geom_boxplot(fill = "skyblue") +
  labs(title = "Value Distribution for Percentage Indicators (0–100)") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

ggplot(acc_df, aes(x = Indicator, y = Value)) +
  geom_boxplot(fill = "orange") +
  scale_y_log10() +
  labs(title = "Value Distribution by Indicator (log scale)") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```
