---
title: "EDA_Child_Mortality_Rates_National_03"
author: "Group K"
date: "`r Sys.Date()`"
output: pdf_document
---
```{r setup, include=FALSE}
library(readr)
library(ggplot2)
library(dplyr)
library(here)
library(tidyr)
library(knitr)
library(skimr)
library(tidyverse)
library(summarytools)
knitr::opts_chunk$set(echo = FALSE, message=FALSE, warning=FALSE)

```

# 1. Loading the dataset 
```{r}
cmr_df <- read_csv(here("raw_data", "child-mortality-rates_national_zaf.csv"))
```
## Dislay the first 5 rows
```{r}
kable(
  head(cmr_df[-1, c("ISO3", "DataId", "Indicator", "Value", "CountryName", "SurveyYear")], 5),
  caption = "First 5 rows of the Access to Health Care Dataset (excluding first row)"
)

```
# 2. Data Overview

## Summary statistics
```{r}
summary_table <- cmr_df %>%
  summarise(across(where(is.numeric),
                   list(mean = ~mean(., na.rm = TRUE),
                        sd   = ~sd(., na.rm = TRUE),
                        min  = ~min(., na.rm = TRUE),
                        max  = ~max(., na.rm = TRUE)))) %>%
  pivot_longer(
    cols = everything(),
    names_to = c("Variable", "Statistic"),
    names_sep = "_",
    values_to = "Value"
  ) %>%
  arrange(Variable)

# Save and display
write_csv(summary_table, "../outputs/summary tables/summary_childM.csv")
kable(summary_table, caption = "Summary Statistics for Numeric Variables in the Dataset")


```

# 3. Data Quality 
```{r}
cmr_df$Value <- as.numeric(cmr_df$Value)
```
## Find duplicated values 
```{r}
sum(duplicated(cmr_df))
```
#Inspect columns for missing/empty data as values and pecentages respectively
```{r}
colSums(is.na(cmr_df))
round(colMeans(is.na(cmr_df)) * 100, 2)
```

## Check for unique values
```{r}
sapply(cmr_df, function(x) length(unique(x)))

```
# 4. Visualizations
## Bar plot of mortality indicators for a specific year

```{r}

cmr_df$Value <- as.numeric(cmr_df$Value)
cmr_df$SurveyYear <- as.numeric(cmr_df$SurveyYear)

ggplot(cmr_df, aes(x = factor(SurveyYear), y = Value, fill = Indicator)) +
  geom_bar(stat = "identity", position = "dodge") +
  theme_minimal() +
  labs(
       x = "Survey Year",
       y = "Rate per 1000 births",
       fill = "Indicator") +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    axis.title.x = element_text(margin = margin(t = 15)),  # move x-axis label up
    axis.title.y = element_text(margin = margin(r = 15))   # move y-axis label right
  )

ggsave("../outputs/visuals/cmr_timeseriesplot.png", width = 6, height = 4)
```

